name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2]
        silverstripe: ['4.12', '5.0']
        include:
          - php: 8.1
            silverstripe: '4.12'
          - php: 8.2
            silverstripe: '4.12'
          - php: 8.1
            silverstripe: '5.0'
          - php: 8.2
            silverstripe: '5.0'

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, intl, pdo_sqlite
        coverage: none

    - name: Validate composer.json
      run: composer validate --strict

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-composer-

    - name: Install dependencies
      run: |
        composer require silverstripe/framework:^${{ matrix.silverstripe }} --no-interaction
        composer install --prefer-dist --no-progress

    - name: Run tests
      run: vendor/bin/phpunit

    - name: Build frontend assets
      run: |
        npm install
        npm run build 